server:
  port: 8090
spring:
  application:
    name: rentacar-user-api-authservice
  datasource:
    url: jdbc:h2:mem:rentacar-userservice
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka