eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
        cloud.gateway.route.RouteDefinitionLocator: INFO

server:
  port: 8080

spring:
  application:
    name: rentacar-user-api-apigateway
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: rentacar-user-api-userservice
          uri: lb://rentacar-user-api-userservice
          predicates:
            - Path=/users/**
#          filters:
#            - JwtAuthenticationFilter
#            - name: CircuitBreaker
#              args:
#                name: rentacar-user-api-userservice
#                fallbackuri: forward:/userServiceFallBack
        - id: rentacar-user-api-carservice
          uri: lb://rentacar-user-api-carservice
          predicates:
            - Path=/car/**
#          filters:
#            - JwtAuthenticationFilter
#            - name: CircuitBreaker
#              args:
#                name: rentacar-user-api-carservice
#                fallbackuri: forward:/carServiceFallBack
        - id: rentacar-user-api-authservice
          uri: lb://rentacar-user-api-authservice
          predicates:
            - Path=/auth/**
#          filters:
#            - JwtAuthenticationFilter
#            - name: CircuitBreaker
#              args:
#                name: rentacar-user-api-authservice
#                fallbackuri: forward:/authServiceFallback

jwt:
  secret: 4509b6310995804bb752cf947c773c6a965a9844502a8da8ea770ef496b3aa5a8fc78825e3fda93baaaa02d22914694ed318a5ada2fa083f23a3cde4a1f574a5


