server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: rentacar-user-api-configservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kcguran/spring-cloud-security-config-server.git
          clone-on-start: true
          default-label: main